"""
Problem 32: 
Write a function mutate to compute all words generated by a single mutation on a given word. 
A mutation is defined as inserting a character, deleting a character, 
replacing a character, or swapping 2 consecutive characters in a string. 
For simplicity consider only letters from a to z.

words = mutate('hello')
'helo' in words
True
'cello' in words
True
'helol' in words
True
"""



# get 如果没有此元素， 则返回设置的健值对的值，并且不包含在原有的字典中。 
d = {'x': 1, 'y': 2, 'z': 3}
d.get('x', 5)
print(d.get('p', 5))
print(d)
print(d['x'])


